
int bitNor(int, int);
int test_bitNor(int, int);
int bitXor(int, int);
int test_bitXor(int, int);
int getByte(int, int);
int test_getByte(int, int);
int copyLSB(int);
int test_copyLSB(int);
int isAsciiDigit(int);
int test_isAsciiDigit(int);
int logicalShift(int, int);
int test_logicalShift(int, int);
int bitCount(int);
int test_bitCount(int);
int bang(int);
int test_bang(int);
int leastBitPos(int);
int test_leastBitPos(int);
int negate(int);
int test_negate(int);
int isNonNegative(int);
int test_isNonNegative(int);
int isLess(int, int);
int test_isLess(int, int);
int isZero(int);
int test_isZero(int);
int addOK(int, int);
int test_addOK(int, int);
